### ISSUE TITLE
Install unison-fsmonitor

### ISSUE THREAD

**Issue by hairmare** [radiorabe/centos-rpm-unison251#3]
It would be awesome if we could also get unison-fsmonitor into the package as well (it's in src/ after the build).

I believe fsmonitor does more watching and less periodical syncing than https://github.com/radiorabe/roaming-homes how it's set up now and I'd like to compare the two solutions side by side.

**Comment by paraenggu** [comment]
Thanks for the report, the `fsmonitor` was one of the main reasons for bumping and building this package :-)
